@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



skinparam classAttributeIconSize 0

hide circle
hide methods



class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Collaborator {
Name
birthdate
admission date
address
contact info
 ID doc type
 ID number
}


class Skill{
name


}

class HRM {
    name
    email
    position
    phone
}




Organization "1" - "n..*" HRM :has  >

HRM "1" - "n..*" Collaborator :assigns >
Collaborator "0" - "n..*" Skill :has >



@enduml