@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resource Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a new collaborator
    activate System

        System --> Employee : requests data (i.e. name,birthdate,admission date,address, contact info,ID doc type )
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : show all data and  request confirmation
    deactivate System



    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml